matrix:
    include:
    - os: osx
      osx_image: xcode8
      install:
        - brew install python3
      script: ./build_and_deploy.sh
      env:
        - DEPLOY_SDIST=true

    - os: linux
      env: 
        - PYTHON_VER=3.6
      install: 
        - docker build -t atari-py-img -f dockerfile.${PYTHON_VER} . 
      script: 
        - docker run -e TRAVIS_TAG=$TRAVIS_TAG -e TWINE_USERNAME=$TWINE_USERNAME -e TWINE_PASSWORD=$TWINE_PASSWORD atari-py-img bash ./build_and_deploy.sh
    

        
