language: python

python:
    - 3.5
    - 3.6
    - 3.7

matrix:
    include:
        - os: linux
          dist: xenial
        
        - os: osx

script:
    - python -c "print('Hello World')"
         
        
